### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by rkaehlert** [clMathLibraries/clRNG#2]
I've built and installed the library as described here on github. My Problem is getting the following errors in the clBuildProgram method when reading the kernel. This happens even when i set up and run the exmaple code. What ive dine wrong? Thanks a lot.

In file included from <kernel>:2:
In file included from C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clR
NG-1.0.0-Windows-x64\cl\include\mrg31k3p.clh:44:
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\clRNG.clh:50:9: error: use of type 'double' requires cl_khr_fp64 exten
sion to be enabled
typedef double cl_double;
        ^
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\clRNG.clh:77:34: error: variadic macros not supported in OpenCL
# define clrngSetErrorString(err, ...) (err)

```
                             ^
```

In file included from <kernel>:2:
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\mrg31k3p.clh:113:9: error: invalid argument type '**attribute**((addre
ss_space(16776963))) clrngMrg31k3pStream *' (aka '**attribute**((address_space(1
6776963))) struct clrngMrg31k3pStream_ *') to unary expression
    if (!destStreams)
        ^~~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\mrg31k3p.clh:114:9: warning: implicit declaration of function 'clrngSe
tErrorString' is invalid in C99
        return clrngSetErrorString(CLRNG_INVALID_VALUE, "clrngMrg31k3pCopyOverSt
reamsFromGlobal(): destStreams cannot be NULL");
               ^
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\mrg31k3p.clh:115:9: error: invalid argument type 'const **global clrng
Mrg31k3pHostStream *' (aka 'const __global struct clrngMrg31k3pHostStream_ *') t
o unary expression
    if (!srcStreams)
        ^~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\mrg31k3p.clh:132:9: error: invalid argument type '__global clrngMrg31k
3pHostStream *' (aka '__global struct clrngMrg31k3pHostStream_ *') to unary expr
ession
    if (!destStreams)
        ^~~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\mrg31k3p.clh:134:9: error: invalid argument type 'const __attribute**(
(address_space(16776963))) clrngMrg31k3pStream *' (aka 'const **attribute**((add
ress_space(16776963))) struct clrngMrg31k3pStream_ *') to unary expression
    if (!srcStreams)
        ^~~~~~~~~~~
In file included from <kernel>:2:
In file included from C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clR
NG-1.0.0-Windows-x64\cl\include\mrg31k3p.clh:155:
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:85:6: error: invalid argument type '**attribute**
((address_space(16776963))) clrngMrg31k3pStream *' (aka '**attribute**((address_
space(16776963))) struct clrngMrg31k3pStream_ *') to unary expression
        if (!destStreams)
            ^~~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:87:6: error: invalid argument type 'const **attri
bute**((address_space(16776963))) clrngMrg31k3pStream *' (aka 'const **attribute
__((address_space(16776963))) struct clrngMrg31k3pStream_ *') to unary expressio
n
        if (!srcStreams)
            ^~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:181:1: error: invalid argument type '__attribute_
_((address_space(16776963))) clrngMrg31k3pStream *' (aka '__attribute**((address
_space(16776963))) struct clrngMrg31k3pStream_ *') to unary expression
IMPLEMENT_GENERATE_FOR_TYPE(cl_float)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:159:7: note: expanded from macro 'IMPLEMENT_GENER
ATE_FOR_TYPE'
                if (!stream) \
                    ^~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:181:1: error: invalid argument type '**attribute_
_((address_space(16776963))) cl_float *' (aka '__attribute**((address_space(1677
6963))) float *') to unary expression
IMPLEMENT_GENERATE_FOR_TYPE(cl_float)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:161:7: note: expanded from macro 'IMPLEMENT_GENER
ATE_FOR_TYPE'
                if (!buffer) \
                    ^~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:181:1: error: invalid argument type '**attribute_
_((address_space(16776963))) clrngMrg31k3pStream *' (aka '__attribute**((address
_space(16776963))) struct clrngMrg31k3pStream_ *') to unary expression
IMPLEMENT_GENERATE_FOR_TYPE(cl_float)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:169:7: note: expanded from macro 'IMPLEMENT_GENER
ATE_FOR_TYPE'
                if (!stream) \
                    ^~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:181:1: error: invalid argument type '**attribute_
_((address_space(16776963))) cl_int *' (aka '__attribute**((address_space(167769
63))) int *') to unary expression
IMPLEMENT_GENERATE_FOR_TYPE(cl_float)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:171:7: note: expanded from macro 'IMPLEMENT_GENER
ATE_FOR_TYPE'
                if (!buffer) \
                    ^~~~~~~
C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
l\include\private/mrg31k3p.c.h:195:6: error: invalid argument type '**attribute_
_((address_space(16776963))) clrngMrg31k3pStream *' (aka '__attribute**((address
_space(16776963))) struct clrngMrg31k3pStream_ *') to unary expression
        if (!streams)
            ^~~~~~~~

**Comment by NabilKem** [comment]
Hi rkaehlert,

this is bug that was fixed on the last commit two days ago, please pull the last version of code and try again.

Thanks
Nabil

**Comment by rkaehlert** [comment]
Hi Nabil,

thanks a lot for your fast response. Ive pulled the latest sources, but still getting errors. Anything else whats wrong?

<b>-11In file included from :2:
In file included from C:\Users\robin\Desktop\clRNG\package/cl/include/mrg31k3p.c
lh:44:
C:\Users\robin\Desktop\clRNG\package/cl/include/clRNG.clh:45:2: error: #error "c
lRNG.clh can be included in device code only"
C:\Users\robin\Desktop\clRNG\package/cl/include/clRNG.clh:79:34: error: variadic
 macros are not allowed in OpenCL
In file included from :2:
C:\Users\robin\Desktop\clRNG\package/cl/include/mrg31k3p.clh:114:9: warning: imp
licit declaration of function 'clrngSetErrorString' is invalid in C99
In file included from :2:
In file included from C:\Users\robin\Desktop\clRNG\package/cl/include/mrg31k3p.c
lh:155:
C:\Users\robin\Desktop\clRNG\package/cl/include/private/mrg31k3p.c.h:98:1: error
: invalid storage-class specifiers in OpenCL</b>

Creating random numbers in host code works perfectly. Its just the kernel making problems.

Thanks very much.
Robin

**Comment by mungerd** [comment]
Hi @rkaehlert ,

Which OpenCL SDK are you using?
We developed the library using the [AMD APP SDK](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/), and their OpenCL C compiler did not know about the `NULL` constant.  So we wrote, for instance:

```
if (!streams)
```

instead of

```
if (streams == NULL)
```

Perhaps we need to make a workaround for this.

**Comment by rkaehlert** [comment]
Hi @mungerd,

ive tried it with both SKDs, first with the Nvidia which i was on before but yesterday i installed the AMD SDK too to see if it works with that, but i got the same errors.

"Use the AMD APP SDK" means for this i use the header files and opencl lib from AMD. I dont know if the compiler used is also the one from AMD. How can i determine which Compiler is used?

btw. i'm developing with Visual Studio 2013 on Windows

Thank you!

**Comment by mungerd** [comment]
Thanks @rkaehlert.
It would help if we were able to reproduce the bug here.  I still can't.

Also, this error is very weird:

> C:\Users\robin\Desktop\clRNG_CPack_Packages\win64\ZIP\clRNG-1.0.0-Windows-x64\c
> l\include\mrg31k3p.clh:114:9: warning: implicit declaration of function 'clrngSe
> tErrorString' is invalid in C99
> return clrngSetErrorString(CLRNG_INVALID_VALUE, "clrngMrg31k3pCopyOverSt
> reamsFromGlobal(): destStreams cannot be NULL");

because `mrg31k3p.clh` includes `clRNG.clh`, which actually defines:

```
#define clrngSetErrorString(err, ...) (err)
```

This is very puzzling to me.

**Comment by rkaehlert** [comment]
The one you mean maybe comes from the error before

<blockquote>C:\Users\robin\Desktop\clRNG\package/cl/include/clRNG.clh:79:34: error: variadic
macros are not allowed in OpenCL</blockquote>

because this

<blockquote>#define clrngSetErrorString(err, ...) (err)></blockquote>

is a variadic macro isnt it?

I'm wondering about this one, because there is no inclusion of clh file outside of device code.

<blockquote>C:\Users\robin\Desktop\clRNG\package/cl/include/clRNG.clh:45:2: error: #error "c
lRNG.clh can be included in device code only"</blockquote>

Maybe i made something wrong when setting up the project. but i couldnt figure out what this could be.

**Comment by NabilKem** [comment]
Hi

can you tell us whats your OpenCL version by printing the content of the "**OPENCL_C_VERSION** " from a Kernel?

printf(" \%d \n", __OPENCL_C_VERSION__);

Thanks
Nabil

**Comment by rkaehlert** [comment]
Do you mean the CL_DEVICE_OPENCL_C_VERSION with clGetDeviceInfo() ?

**Comment by NabilKem** [comment]
Because we are testing on the existance of  __OPENCL_C_VERSION__ ( at clRNG.clh:45)

 i'd like that you execute the follwoing instruction inside a Kernel to check if you get it printed out or not : printf("   \%d \n  ", __OPENCL_C_VERSION__);

Thanks

**Comment by rkaehlert** [comment]
I get the following error:

ptxas application ptx input, line 62; error   : Call has wrong number of paramet
ers
ptxas fatal   : Ptx assembly aborted due to errors

**Comment by NabilKem** [comment]
I think if you can't get the __OPENCL_C_VERSION__ printed out from a testing Kernel (and independant from clRNG), this means that you have an issue with your Open CL installation, pls double check that, and let us know.

Thanks

**Comment by NabilKem** [comment]
Ok can you confirm that you can execute this code in a testing kernel (without using clRNG) just to check that your envirnoement is OK ?

//We used AMD APP SDK to develop the lib

#pragma OPENCL EXTENSION cl_amd_printf : enable 

__kernel void TestOpenClVersion(){
printf(" \%d \n", __OPENCL_C_VERSION__);
}

Thanks

**Comment by rkaehlert** [comment]
I dont get it to work. So may youre right and my environment ist wrong. but anything before i tried to use clRNG everything worked fine. As i mentioned before i was using the Nvidia SDK so long.

Is it a fact that the clRNG just work with the AMD SDK? What do i need to do to use the AMD instead of the Nvidia SDK? I've changed the library an header-files to the AMD ones. Is there anything else i need to do in my project setup?

When is use my Intel Core Processor as OpenCL Device i get the following error

<blockquote>:1:42: warning: unknown OpenCL extension 'cl_amd_printf' - ignoring
:4:20: error: use of undeclared identifier '__OPENCL_C_VERSION__'</blockquote>

When i use my GT540m as Device i get

<blockquote>ptxas application ptx input, line 40; error   : Call has wrong number of paramet
ers
ptxas fatal   : Ptx assembly aborted due to errors</blockquote>

**Comment by NabilKem** [comment]
We developped and tested the clRNG on the "AMD APP SDK" which you can install from this link : http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/

You should be all set after using this SDK.
Thanks for the feedback.

**Comment by rkaehlert** [comment]
I've installed the AMD APP SDK already and i am using it on the project where i need the clRNG. But i get this strange errors from the first post.

Creating Random numbers on host side works fine, but if i include the <mrg31k3p.clh> in my kernel the clBuildProgram fails.

**Comment by rkaehlert** [comment]
Is there a minium OpenCL version which a device has to support for running clRNG?

**Comment by mungerd** [comment]
I believe we haven't tried versions below OpenCL 1.2.

**Comment by rkaehlert** [comment]
My graphics Card supports OpenCL 1.1
But could that be the problem for the many compiler errors?

**Comment by NabilKem** [comment]
Yes could be, but can you check if you have this extension enabled ?: cl_amd_printf
the following error indicates that you have an issue with the AMD SDK, as this extension is not found

:1:42: warning: unknown OpenCL extension 'cl_amd_printf' - ignoring :4:20: error: use of undeclared identifier '**OPENCL_C_VERSION**'

Thanks

**Comment by rkaehlert** [comment]
Ive searched a bit around and it seems that just AMD Devices supports the cl_amd_printf extension.
But what if i want to run the kernel on a Nvidia Graphics Card?

**Comment by rkaehlert** [comment]
Ok i figured out whats the problem. It seems that AMDAPPSDK installs a virtual OpenCL device which uses the local CPU as processor. Now the important thing:

If i select this AMD Device for the kernel execution, everthing is fine. Printf works and no compiler errors. When i select my nvidia graphics cars as device, its messed up.

At the moment i dont know if it is because its a Nvidia Device or if its because the graphics card just supports opencl 1.1.

So i can confirm you that my AMD environment is set up correclty but im not able to run the clRNG on my graphics card. do you have any solution for this?

Thanks very very much for your help today.

**Comment by axisse** [comment]
Hello, I think I have the same problem as rkaehlert.
"variadic macros not supported in OpenCL". I try to build my .cl on the INTEL INDE code builder. The graphic card on my CPU is defined as device and uses OpenCL 2.0.
Have you succeeded to fixed it?
